#ifndef W5500_DEFS_H
#define W5500_DEFS_H

#define ETH_ACCESS_MODE_RD             0
#define ETH_ACCESS_MODE_WR             1

#define ETH_OPMODE_VDLM_NB             0
#define ETH_OPMODE_FDLM_1B             1
#define ETH_OPMODE_FDLM_2B             2
#define ETH_OPMODE_FDLM_4B             3

#define ETH_SEL_COMM_REG            0x00
#define ETH_SEL_SOC0_REG            0x01
#define ETH_SEL_SOC0_TXB            0x02
#define ETH_SEL_SOC0_RXB            0x03
#define ETH_SEL_SOC1_REG            0x05
#define ETH_SEL_SOC1_TXB            0x06
#define ETH_SEL_SOC1_RXB            0x07
#define ETH_SEL_SOC2_REG            0x09
#define ETH_SEL_SOC2_TXB            0x0a
#define ETH_SEL_SOC2_RXB            0x0b
#define ETH_SEL_SOC3_REG            0x0d
#define ETH_SEL_SOC3_TXB            0x0e
#define ETH_SEL_SOC3_RXB            0x0f
#define ETH_SEL_SOC4_REG            0x11
#define ETH_SEL_SOC4_TXB            0x12
#define ETH_SEL_SOC4_RXB            0x13
#define ETH_SEL_SOC5_REG            0x15
#define ETH_SEL_SOC5_TXB            0x16
#define ETH_SEL_SOC5_RXB            0x17
#define ETH_SEL_SOC6_REG            0x19
#define ETH_SEL_SOC6_TXB            0x1a
#define ETH_SEL_SOC6_RXB            0x1b
#define ETH_SEL_SOC7_REG            0x1d
#define ETH_SEL_SOC7_TXB            0x1e
#define ETH_SEL_SOC7_RXB            0x1f

#define ETH_REG_MR                  0x00
#define ETH_REG_GAR0                0x01
#define ETH_REG_GAR1                0x02
#define ETH_REG_GAR2                0x03
#define ETH_REG_GAR3                0x04
#define ETH_REG_SUBR0               0x05
#define ETH_REG_SUBR1               0x06
#define ETH_REG_SUBR2               0x07
#define ETH_REG_SUBR3               0x08
#define ETH_REG_SHAR0               0x09
#define ETH_REG_SHAR1               0x0a
#define ETH_REG_SHAR2               0x0b
#define ETH_REG_SHAR3               0x0c
#define ETH_REG_SHAR4               0x0d
#define ETH_REG_SHAR5               0x0e
#define ETH_REG_SIRP0               0x0f
#define ETH_REG_SIRP1               0x10
#define ETH_REG_SIRP2               0x11
#define ETH_REG_SIRP3               0x12
#define ETH_REG_INTLEVEL0           0x13
#define ETH_REG_INTLEVEL1           0x14
#define ETH_REG_IR                  0x15
#define ETH_REG_IMR                 0x16
#define ETH_REG_SIR                 0x17
#define ETH_REG_SIMR                0x18
#define ETH_REG_RTR0                0x19
#define ETH_REG_RTR1                0x1a
#define ETH_REG_RCR                 0x1b
#define ETH_REG_PTIMER              0x1c
#define ETH_REG_PMAGIC              0x1d
#define ETH_REG_PHAR0               0x1e
#define ETH_REG_PHAR1               0x1f
#define ETH_REG_PHAR2               0x20
#define ETH_REG_PHAR3               0x21
#define ETH_REG_PHAR4               0x22
#define ETH_REG_PHAR5               0x23
#define ETH_REG_PSID0               0x24
#define ETH_REG_PSID1               0x25
#define ETH_REG_PMRU0               0x26
#define ETH_REG_PMRU1               0x27
#define ETH_REG_UIPR0               0x28
#define ETH_REG_UIPR1               0x29
#define ETH_REG_UIPR2               0x2a
#define ETH_REG_UIPR3               0x2b
#define ETH_REG_UPORTR0             0x2c
#define ETH_REG_UPORTR1             0x2d
#define ETH_REG_PHYCFGR             0x2e
#define ETH_REG_VERSIONR            0x39

#define ETH_REG_SN_MR               0x00
#define ETH_REG_SN_CR               0x01
#define ETH_REG_SN_IR               0x02
#define ETH_REG_SN_SR               0x03
#define ETH_REG_SN_PORT0            0x04
#define ETH_REG_SN_PORT1            0x05
#define ETH_REG_SN_DHAR0            0x06
#define ETH_REG_SN_DHAR1            0x07
#define ETH_REG_SN_DHAR2            0x08
#define ETH_REG_SN_DHAR3            0x09
#define ETH_REG_SN_DHAR4            0x0a
#define ETH_REG_SN_DHAR5            0x0b
#define ETH_REG_SN_DIPR0            0x0c
#define ETH_REG_SN_DIPR1            0x0d
#define ETH_REG_SN_DIPR2            0x0e
#define ETH_REG_SN_DIPR3            0x0f
#define ETH_REG_SN_DPORT0           0x10
#define ETH_REG_SN_DPORT1           0x11
#define ETH_REG_SN_MSSR0            0x12
#define ETH_REG_SN_MSSR1            0x13
#define ETH_REG_SN_TOS              0x15
#define ETH_REG_SN_TTL              0x16
#define ETH_REG_SN_RXBUF_SIZE       0x1e
#define ETH_REG_SN_TXBUF_SIZE       0x1f
#define ETH_REG_SN_TX_FSR0          0x20
#define ETH_REG_SN_TX_FRS1          0x21
#define ETH_REG_SN_TX_RD0           0x22
#define ETH_REG_SN_TX_RD1           0x23
#define ETH_REG_SN_TX_WR0           0x24
#define ETH_REG_SN_TX_WR1           0x25
#define ETH_REG_SN_RX_RSR0          0x26
#define ETH_REG_SN_RX_RSR1          0x27
#define ETH_REG_SN_RX_RD0           0x28
#define ETH_REG_SN_RX_RD1           0x29
#define ETH_REG_SN_RX_WR0           0x2a
#define ETH_REG_SN_RX_WR1           0x2b
#define ETH_REG_SN_IMR              0x2c
#define ETH_REG_SN_FRAG0            0x2d
#define ETH_REG_SN_FRAG1            0x2e
#define ETH_REG_SN_KPALVTR          0x2f

#define ETH_SN_CR_OPEN              0x01
#define ETH_SN_CR_LISTEN            0x02
#define ETH_SN_CR_CONNECT           0x04
#define ETH_SN_CR_DISCON            0x08
#define ETH_SN_CR_CLOSE             0x10
#define ETH_SN_CR_SEND              0x20
#define ETH_SN_CR_SEND_MAC          0x21
#define ETH_SN_CR_SEND_KEEP         0x22
#define ETH_SN_CR_RECV              0x40

#define ETH_SN_SR_SOCK_CLOSED       0x00
#define ETH_SN_SR_SOCK_INIT         0x13
#define ETH_SN_SR_SOCK_LISTEN       0x14
#define ETH_SN_SR_SOCK_ESTABLISHED  0x17
#define ETH_SN_SR_SOCK_CLOSE_WAIT   0x1c
#define ETH_SN_SR_SOCK_UDP          0x22
#define ETH_SN_SR_SOCK_MACRAW       0x42
#define ETH_SN_SR_SOCK_SYNSENT      0x15
#define ETH_SN_SR_SOCK_SYNRECV      0x16
#define ETH_SN_SR_SOCK_FIN_WAIT     0x18
#define ETH_SN_SR_SOCK_CLOSING      0x1a
#define ETH_SN_SR_SOCK_TIME_WAIT    01xb
#define ETH_SN_SR_SOCK_LAST_ACK     0x1d

#define ETH_MSSR_NORMAL_TCP_MAX_MTU 1460
#define ETH_MSSR_NORMAL_UDP_MAX_MTU 1472
#define ETH_MSSR_PPPOE_TCP_MAX_MTU  1452
#define ETH_MSSR_PPPOE_UDP_MAX_MTU  1464
#define ETH_MSSR_MACRAW             1514

#define ETH_BIT_RST               _BV(7)
#define ETH_BIT_WOL               _BV(5)
#define ETH_BIT_PB                _BV(4)
#define ETH_BIT_PPPOE_MODE        _BV(3)
#define ETH_BIT_FARP              _BV(1)
#define ETH_BIT_CONFLICT          _BV(7)
#define ETH_BIT_UNREACH           _BV(6)
#define ETH_BIT_PPPOE_CON_CLOSE   _BV(5)
#define ETH_BIT_MP                _BV(4)
#define ETH_BIT_IM_IR7            _BV(7)
#define ETH_BIT_IM_IR6            _BV(6)
#define ETH_BIT_IM_IR5            _BV(5)
#define ETH_BIT_IM_IR4            _BV(4)
#define ETH_BIT_S7_INT            _BV(7)
#define ETH_BIT_S6_INT            _BV(6)
#define ETH_BIT_S5_INT            _BV(5)
#define ETH_BIT_S4_INT            _BV(4)
#define ETH_BIT_S3_INT            _BV(3)
#define ETH_BIT_S2_INT            _BV(2)
#define ETH_BIT_S1_INT            _BV(1)
#define ETH_BIT_S0_INT            _BV(0)
#define ETH_BIT_S7_IMR            _BV(7)
#define ETH_BIT_S6_IMR            _BV(6)
#define ETH_BIT_S5_IMR            _BV(5)
#define ETH_BIT_S4_IMR            _BV(4)
#define ETH_BIT_S3_IMR            _BV(3)
#define ETH_BIT_S2_IMR            _BV(2)
#define ETH_BIT_S1_IMR            _BV(1)
#define ETH_BIT_S0_IMR            _BV(0)
#define ETH_BIT_OPMD              _BV(6)
#define ETH_BIT_OPMDC5            _BV(5)
#define ETH_BIT_OPMDC4            _BV(4)
#define ETH_BIT_OPMDC3            _BV(3)
#define ETH_BIT_DPX               _BV(2)
#define ETH_BIT_SPD               _BV(1)
#define ETH_BIT_LNK               _BV(0)
#define ETH_BIT_MULTI_MFEN        _BV(7)
#define ETH_BIT_BCASTB            _BV(6)
#define ETH_BIT_ND_MC_MMB         _BV(5)
#define ETH_BIT_UCASTB_MIP6B      _BV(4)
#define ETH_BIT_P3                _BV(3)
#define ETH_BIT_P2                _BV(2)
#define ETH_BIT_P1                _BV(1)
#define ETH_BIT_P0                _BV(0)
#define ETH_BIT_SEND_OK           _BV(4)
#define ETH_BIT_TIMEOUT           _BV(3)
#define ETH_BIT_RECV              _BV(2)
#define ETH_BIT_DISCON            _BV(1)
#define ETH_BIT_CON               _BV(0)

#endif